[project]
authors = [
    {name = "Maksim Litvinov", email = "litvinovmksm@gmail.com"},
]
requires-python = "<4.0,>=3.12"
name = "python-example-app"
version = "0.1.0"
description = "Example application"
readme = "README.md"

[tool.uv]
dev-dependencies = [
    "ruff>=0.7.1",
    "pytest>=8.3.3",
]
